### ISSUE TITLE
Build error upgrading to Flutter 3.10.0

### ISSUE THREAD

**Issue by Ciock** [Tkko/Flutter_dismissible_page#29]
Error:

> Target dart2js failed: Exception: ../../../../../.pub-cache/git/Flutter_dismissible_page-5dde9c12a03d82e8d3d4583ef929422cd21e606b/lib/src/multi_axis_dismissible_page.dart:61:10:
> Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin.
>     with Drag, SingleTickerProviderStateMixin, _DismissiblePageMixin {

**Comment by Tkko** [comment]
@Ciock What is the package version?

**Comment by Ciock** [comment]
I'm on this branch because of this issue https://github.com/Tkko/Flutter_dismissible_page/issues/14
```
  dismissible_page: # https://github.com/Tkko/Flutter_dismissible_page/issues/14
    git:
      url: https://github.com/Tkko/Flutter_dismissible_page
      ref: feature/scrolable_dismissible
```
